version: "3.8"

services:
  phantom-room:
    build: .
    container_name: phantom-room-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PHANTOM_JWT_SECRET=phantom_production_signed_secret_key_change_me_in_prod
    volumes:
      - phantom_uploads:/app/uploads
    security_opt:
      - no-new-privileges:true

volumes:
  phantom_uploads:
